[package]
name = "manyfest"
version = "0.1.0"
authors = ["thegitm8 <mail@antlike.tech>"]

[[bin]]
name = "mf"
path = "src/main.rs"

[dependencies]
serde = "1.0.21"
serde_json = "1.0"
serde_derive = "1.0.21"